name: Build Clicker IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build IPA
        run: |
          xcodebuild -project Clicker.xcodeproj -scheme Clicker -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Clicker.xcarchive
          mkdir -p Payload
          cp -r $PWD/build/Clicker.xcarchive/Products/Applications/*.app Payload/
          zip -r Clicker.ipa Payload
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: Clicker-v2
          path: Clicker.ipa
